### ISSUE TITLE
Workspace example doesn't work

### ISSUE THREAD

**Issue by gsagula** [masmovil/masorange_rules_helm#64]
https://github.com/masmovil/bazel-rules#getting-started

```
 bazel build //...
INFO: Invocation ID: 097bf422-1e4e-4758-945c-c30c6f28495b
ERROR: error loading package '': Every .bzl file must have a corresponding package, but '@com_github_masmovil_bazel_rules//repositories:repositories.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
INFO: Elapsed time: 0.521s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
gsagula@mlll9944:~/src/magicleap/service-template-go$ bazel build //...
INFO: Invocation ID: 0690c958-1b35-4c44-a92f-737871a9023f
INFO: Repository com_github_masmovil_bazel_rules instantiated at:
  /home/gsagula/src/magicleap/service-template-go/WORKSPACE:102:15: in <toplevel>
Repository rule git_repository defined at:
  /home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_github_masmovil_bazel_rules':
   Traceback (most recent call last):
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 104, column 10, in _update
                reset(ctx, git_repo)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 148, column 9, in reset
                _git(ctx, git_repo, "reset", "--hard", git_repo.reset_ref)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, column 15, in _git
                _error(ctx.name, start + list(args), st.stderr)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git reset --hard commit-ref' while working with @com_github_masmovil_bazel_rules:
fatal: ambiguous argument 'commit-ref': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR: /home/gsagula/src/magicleap/service-template-go/WORKSPACE:102:15: fetching git_repository rule //external:com_github_masmovil_bazel_rules: Traceback (most recent call last):
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
                update = _clone_or_update(ctx)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
                git_ = git_repo(ctx, directory)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
                _update(ctx, git_repo)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 104, column 10, in _update
                reset(ctx, git_repo)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 148, column 9, in reset
                _git(ctx, git_repo, "reset", "--hard", git_repo.reset_ref)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, column 15, in _git
                _error(ctx.name, start + list(args), st.stderr)
        File "/home/gsagula/.cache/bazel/_bazel_gsagula/2f04c0081ad09c5c6296366d26717d29/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git reset --hard commit-ref' while working with @com_github_masmovil_bazel_rules:
fatal: ambiguous argument 'commit-ref': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
ERROR: no such package '@com_github_masmovil_bazel_rules//repositories': error running 'git reset --hard commit-ref' while working with @com_github_masmovil_bazel_rules:
fatal: ambiguous argument 'commit-ref': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by danigar** [comment]
Hi, @gsagula! Thanks for creating this issue. I would say this is already solved with new released rules v1.

**Comment by CarlosGamezF** [comment]
The WORKSPACE snippet this issue refers to belonged to the pre-1.0 README (`com_github_masmovil_bazel_rules` with a `commit-ref` placeholder). Since the v1 rewrite (#70) the installation instructions are generated for every release and published in the release notes, for both bzlmod and WORKSPACE:

- https://github.com/masmovil/masorange_rules_helm/releases/tag/v1.8.2 (`bazel_dep(name = "masorange_rules_helm", version = "1.8.2")`, or `http_archive` + `masorange_rules_helm_repositories()` + `masorange_rules_helm_configure()` for WORKSPACE)

The README points to the releases page for the current snippet. Closing as solved; please reopen if the current instructions fail for you.
